[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
showErrorDetails = true

[runner]
enforceSerializableSessionState = false
postScriptGC = false

[theme]
base = "light"
primaryColor = "#CC1E1E"
backgroundColor = "#F4F6FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1B2266"
font = "sans serif"
