from ui.theme import aplicar_tema, user_header
from ui.components import (
    page_banner,
    section_header,
    kpi_row,
    module_card,
    alert,
    status_badge,
    divider,
    welcome_banner,
    client_header,
    kpi_card,
    gauge_riesgo,
    credit_bar,
    facturas_table,
    payment_info,
    ESTATUS_CFG, 
    status_badge_html, 
    historial_timeline, 
    solicitud_card,
    solicitudes_table,
)
